### ISSUE TITLE
Feature Request: Add reactions for main post

### ISSUE THREAD

**Issue by wgyt** [laymonage/giscus#92]
This feature would show reactions to the main post above comments and allow a user to add reactions. This could be optional or enabled by default. Something that could look like this: 
![image](https://user-images.githubusercontent.com/68466727/120120707-0dad7680-c16d-11eb-9d00-ad29395a7994.png)
*image taken from https://github.com/utterance/utterances/pull/340*

**Comment by laymonage** [comment]
This is a good idea, thanks @wgyt! This shouldn't be too hard to implement. I'll need to think about the design (e.g. show only non-zero reactions, where to display the sign-in information, etc.). If you have an input, feel free to let me know.

**Comment by wgyt** [comment]
@laymonage I was thinking that the design should look something like this:
![image](https://user-images.githubusercontent.com/68466727/120192781-9d910600-c1e9-11eb-8809-23f406e927e2.png)
and if you aren't logged in:
![image](https://user-images.githubusercontent.com/68466727/120193805-d2ea2380-c1ea-11eb-9179-0d2edd3af2c9.png)
if you hover over it, it uses the disabled cursor and alt text to tell the user to login.

**Comment by laymonage** [comment]
@wgyt Thanks for the suggestion of using the `not-allowed` cursor and the tooltip message! However, I think that the reaction buttons and the comments count shouldn't be in the same line. The comments count will jump around if we have many reactions.

I've made a WIP at #93, you can try it out at the deploy preview. Thanks!

**Comment by laymonage** [comment]
The feature has been shipped! It's enabled by default unless `data-reactions-enabled="0"`. Thanks again!

**Comment by deadcoder0904** [comment]
@laymonage curious why you went with `0` & `1`. Why not `true` & `false`?

**Comment by laymonage** [comment]
@deadcoder0904 as it would be passed on as query params to https://giscus.app/widget, I remember there were several reasons, but here are the ones on top off my head:

- It reduces the number of characters. We're also passing the `<meta>` description, which can be long. There's a limit to the URL string in browsers. If we were to add more options in the future, it's good to keep the query params as small as possible.
- Using `true` or `false` limits it to exclusively two options. I was thinking we *might* want to add an option to disable reactions entirely (on all comments), which can be option `2`. Or, if we want to enable reactions on the main post *only*, that can be option `3`, etc. Though... as the custom CSS support has landed, features can be turned on and off by hiding the elements via CSS.
- I can parse it using `Boolean(+query.reactionsEnabled)`. With `true` and `false`, I would have to do something like `Boolean(query.reactionsEnabled === "true")`. Which isn't that different, but if I were to make it case-insensitive, I would have to do something like `Boolean(query.reactionsEnabled.toLowerCase() === "true")`. If `query.reactionsEnabled` is `undefined`, or if Next.js parses it as an array of strings because there's a comma in the value, I'd have to handle that too (or let it throw an error when calling `.toLowerCase()`).
  With `0` and `1`, there's not much room for errors. Using `Boolean(+query.reactionsEnabled)`, the result is always `true` or `false`, and I can just remove the `Boolean()` if I want to have more options, and just fall back to `1` if `+query.reactionsEnabled` is `NaN`.

**Comment by deadcoder0904** [comment]
1. Nope, I don't think it'll be that long.
2. You can have `true` & `false` & then a `string` if you want to support other options
3. Nope
4. Nope

Not sure I find any to be "real issues" but it's not a huge problem even though `true` & `false` makes more sense but probably every programmer knows what `0` & `1` is :)

**Comment by laymonage** [comment]
1. You'll never know what users put in their meta tags. Description isn't a title, it **can** be long and still make sense. Telling people how they should write their code is not in my power, and that's not my business. I just provide the service, and I try my best to make it work with the limitations/conditions that may arise. Anyway, I haven't set a limit, which I think I should, as I think [this line](https://github.com/utterance/utterances/blob/master/src/client.ts#L43-L47) in utterances' client script was there for a reason.
2. Yes, but then there's not much meaning in what `true` and `false` is. Might as well just use string for all values :)
3. What's "Nope" about it? Care to explain? :)
4. I didn't write a fourth point.

> every programmer knows what 0 & 1 is :)

Exactly :)

**Comment by deadcoder0904** [comment]
@laymonage I just don't think the points support the arguments you were making in this post although you probably had a good reason back then. As I said, it's not a big of an issue :)

> I didn't write a fourth point.

Damn, how didn't I see that 😂 

Oh I thought `0` & `1` was the 4th point 🤦

**Comment by laymonage** [comment]
Well, there's no defined standard for boolean values in query params. What works for me may not work for you.  You can always fork the repository if you want to change stuff. So, let's just agree to disagree.
